# -*- coding: utf-8 -*-
"""Sleep Efficiency ML

Automatically generated by Colab.



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Sleep_Efficiency.csv')

df

df.isnull().sum()


"""

age_efficiency_df = df[['Age', 'Sleep efficiency']]
age_efficiency_df

def scatter_plots(df, col1, col2):
    fig, ax = plt.subplots(figsize=(8,4))
    ax.scatter(df[col1], df[col2])
    ax.set_xlabel(col1)
    ax.set_ylabel(col2)
    plt.title("Age vs. Sleep Efficiency")
    plt.show()

scatter_plots(age_efficiency_df, 'Age', 'Sleep efficiency')

gender_efficiency_df = df[['Gender', 'Sleep efficiency']]
gender_efficiency_df

cleanup_nums = {"Gender":     {'Female': 1, 'Male': 0}}
gender_efficiency_df.replace(cleanup_nums, inplace=True)
gender_efficiency_df.head()

def iqr(vals):
    outliers = []
    q1 = vals.quantile(0.25)
    q3 = vals.quantile(0.75)
    iqr = q3-q1
    Lower_tail = q1 - 1.5 * iqr
    Upper_tail = q3 + 1.5 * iqr
    for i, v in enumerate(vals):
        if v > Upper_tail or v < Lower_tail:
            outliers.append(i)
    return outliers

female_efficiency_df = gender_efficiency_df[gender_efficiency_df['Gender'] == 1]
outliers = iqr(female_efficiency_df['Sleep efficiency'])
female_efficiency_df = female_efficiency_df.drop(outliers)
female_efficiency_df

male_efficiency_df = gender_efficiency_df[gender_efficiency_df['Gender'] == 0]
outliers = iqr(male_efficiency_df['Sleep efficiency'])
male_efficiency_df = male_efficiency_df.drop(outliers)
male_efficiency_df

def female_efficiency_box_plot(df, col):
    plt.clf()
    plt.figure(figsize=(4, 4))
    plt.title("Female Sleep Efficiency")
    plt.ylabel(col)
    sns.boxplot(df[col])
    plt.show()

female_efficiency_box_plot(female_efficiency_df, 'Sleep efficiency')

def male_efficiency_box_plot(df, col):
    plt.clf()
    plt.figure(figsize=(4, 4))
    plt.title("Male Sleep Efficiency")
    plt.ylabel(col)
    sns.boxplot(df[col].values)
    plt.show()

male_efficiency_box_plot(male_efficiency_df, 'Sleep efficiency')

sns.boxplot(male_efficiency_df['Sleep efficiency'].values)
plt.show()

male_efficiency_df.head()

male_efficiency_df['Sleep efficiency']

sns.boxplot(male_efficiency_df['Sleep efficiency'].values)
plt.show()

male_efficiency_df['Sleep efficiency'].values

plt.figure(figsize=[19,10])
sns.heatmap(df.corr(method='pearson'), annot=True).set(title='Correlation Matrix for Sleep Efficiency')

only_time_wakeup = df['Wakeup time'].values
for i in range(int(only_time_wakeup.size)):
  only_time_wakeup[i] = only_time_wakeup[i][11:18]
df

df['Awakenings'].fillna(df['Awakenings'].median(), inplace=True)
df.isnull().sum()

age_sorted_df = df.sort_values(by=['Age'], axis=0)
age_sorted_df['Alcohol consumption'].fillna(method="backfill", inplace=True)
age_sorted_df['Exercise frequency'].fillna(method="backfill", inplace=True)
age_sorted_df = age_sorted_df.drop('Caffeine consumption', axis = 'columns')
age_sorted_df.isnull().sum()

scatter_plots(age_sorted_df, 'Alcohol consumption', 'Sleep efficiency')

age_sorted_df

mean_alcohol_df = age_sorted_df[['Alcohol consumption', 'Sleep efficiency']]
mean_alcohol_df
mean_alcohol = []
for i in range(6):
  mean_alcohol.append(mean_alcohol_df[mean_alcohol_df['Alcohol consumption'] == i].drop(columns=['Alcohol consumption']).values.mean())
print(mean_alcohol)

indices = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
fig, ax = plt.subplots(figsize=(8,4))
ax.scatter(indices, mean_alcohol)
ax.set_xlabel('Alcohol Consumption')
ax.set_ylabel('Mean Sleep efficiency')
plt.title("Alcohol Consumption vs. Mean Sleep Efficiency")
plt.show()

mean_alcohol_adjusted = [0, 1, 2, 3, 4, 5]
for i in range(6):
  mean_alcohol_adjusted[i] = mean_alcohol[i] - 0.5
plt.bar(indices, mean_alcohol_adjusted, 0.8, 0.5)
plt.xlabel('Alcohol Consumption (oz.)')
plt.ylabel('Mean Sleep Efficiency')
plt.title('Alcohol Consumption vs. Mean Sleep Efficiency')



mean_exercise_df = age_sorted_df[['Exercise frequency', 'Sleep efficiency']]
mean_exercise = []
for i in range(6):
  mean_exercise.append(mean_exercise_df[mean_exercise_df['Exercise frequency'] == i].drop(columns=['Exercise frequency']).values.mean())
print(mean_exercise)

mean_exercise_adjusted = [0, 1, 2, 3, 4, 5]
for i in range(6):
  mean_exercise_adjusted[i] = mean_exercise[i] - 0.7
plt.bar(indices, mean_exercise_adjusted, 0.8, 0.7)
plt.xlabel('Exercise Frequency (times per week)')
plt.ylabel('Mean Sleep Efficiency')
plt.title('Exercise Frequency vs. Mean Sleep Efficiency')

mean_exercise_df['Exercise frequency'].unique()
